name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/zephyrproject-rtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: Arduino-Zephyr-API

      - name: Initialize
        working-directory: Arduino-Zephyr-API
        run: |
          west init -m https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core.git
          west update
          git clone https://github.com/arduino/ArduinoCore-API.git ArduinoCore-API
          cp -r ArduinoCore-API/api modules/lib/Arduino-Zephyr-API/cores/arduino/.

      - name: Build fade
        working-directory: Arduino-Zephyr-API
        run: |
          west build -p -b arduino_nano_33_ble_sense samples/fade

      - name: Build i2cdemo
        working-directory: Arduino-Zephyr-API
        run: |
          west build -p -b arduino_nano_33_ble_sense samples/i2cdemo

      - name: Build adc
        working-directory: Arduino-Zephyr-API
        run: |
          west build -p -b beagleconnect_freedom samples/analog_input

